spring.datasource.url=jdbc:postgresql://ep-small-salad-acek6rvf-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_e1mRp7ZzQtcA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=newgate861@gmail.com
spring.mail.password=vadynytycszovllm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=https://yildiraf-barron.atheriscyber.com